import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { learningApi } from '../../api/learning.api.js';
import { queryKeys } from '../../api/query-keys.js';
import { InlineError, LoadingSkeleton } from '../common/States.jsx';

const secondsLeft = (expiresAt) => expiresAt ? Math.max(0, Math.ceil((new Date(expiresAt).getTime() - Date.now()) / 1000)) : null;
const clock = (seconds) => seconds === null ? 'No time limit' : `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
const initialResponse = (question) => question.response || ({ optionIds: [], text: '', numericValue: '', numericUnit: '', pairs: [], items: [] });
const resultText = (attempt) => attempt.pendingManualGrading ? 'Your automatically graded answers have been processed. Final results will be available after teacher grading.' : attempt.passed === true ? 'Passed' : attempt.passed === false ? 'Not passed' : 'Submitted';

const EssayInput = ({ disabled, question, response, saving, onSave }) => {
  const [draft, setDraft] = useState(response.text || ''); const words = draft.trim() ? draft.trim().split(/\s+/).length : 0;
  return <div><textarea aria-label="Essay response" defaultValue={draft} disabled={disabled || saving} onBlur={(event) => onSave({ text: event.target.value })} onChange={(event) => setDraft(event.target.value)} rows="10" /><small>{words} words{question.essayConfig?.maximumWords ? ` / ${question.essayConfig.maximumWords}` : ''}</small></div>;
};

const QuestionInput = ({ question, disabled, onSave, saving }) => {
  const response = initialResponse(question);
  const choose = (optionId, multiple) => onSave({ optionIds: multiple ? (response.optionIds.includes(optionId) ? response.optionIds.filter((id) => id !== optionId) : [...response.optionIds, optionId]) : [optionId] });
  if (['single_choice', 'true_false'].includes(question.questionType)) return <fieldset disabled={disabled || saving}><legend className="sr-only">Choose an answer</legend>{question.options.map((option) => <label className="quiz-option" key={option.id}><input checked={response.optionIds.includes(option.id)} name={`question-${question.id}`} onChange={() => choose(option.id, false)} type="radio" /> <span dangerouslySetInnerHTML={{ __html: option.optionText }} /></label>)}</fieldset>;
  if (question.questionType === 'multiple_choice') return <fieldset disabled={disabled || saving}><legend className="sr-only">Choose all answers that apply</legend>{question.options.map((option) => <label className="quiz-option" key={option.id}><input checked={response.optionIds.includes(option.id)} onChange={() => choose(option.id, true)} type="checkbox" /> <span dangerouslySetInnerHTML={{ __html: option.optionText }} /></label>)}</fieldset>;
  if (question.questionType === 'short_answer') return <textarea aria-label="Short answer" defaultValue={response.text || ''} disabled={disabled || saving} onBlur={(event) => onSave({ text: event.target.value })} rows="3" />;
  if (question.questionType === 'numeric') return <div className="quiz-numeric"><input aria-label="Numeric answer" defaultValue={response.numericValue || ''} disabled={disabled || saving} inputMode="decimal" onBlur={(event) => onSave({ value: event.target.value, unit: response.numericUnit || '' })} /><input aria-label="Unit" defaultValue={response.numericUnit || ''} disabled={disabled || saving} onBlur={(event) => onSave({ value: response.numericValue || '', unit: event.target.value })} placeholder="Unit (optional)" /></div>;
  if (question.questionType === 'matching') { const current = new Map((response.pairs || []).map((pair) => [pair.promptId, pair.matchId])); return <div className="quiz-matching">{question.matchingPrompts.map((prompt) => <label key={prompt.id}><span>{prompt.promptText}</span><select disabled={disabled || saving} onChange={(event) => { const pairs = question.matchingPrompts.map((item) => ({ promptId: item.id, matchId: item.id === prompt.id ? event.target.value : current.get(item.id) })).filter((item) => item.matchId); onSave({ pairs }); }} value={current.get(prompt.id) || ''}><option value="">Select a match</option>{question.matchingChoices.map((choice) => <option key={choice.id} value={choice.id}>{choice.matchText}</option>)}</select></label>)}</div>; }
  if (question.questionType === 'ordering') { const current = response.items?.length ? [...response.items].sort((a, b) => a.position - b.position).map((item) => item.itemId) : question.orderingItems.map((item) => item.id); const move = (index, direction) => { const next = [...current], target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; onSave({ items: next.map((itemId, position) => ({ itemId, position: position + 1 })) }); }; return <ol className="quiz-ordering">{current.map((id, index) => { const item = question.orderingItems.find((candidate) => candidate.id === id); return <li key={id}><span>{item?.itemText}</span><button disabled={disabled || saving || index === 0} onClick={() => move(index, -1)} type="button">Move up</button><button disabled={disabled || saving || index === current.length - 1} onClick={() => move(index, 1)} type="button">Move down</button></li>; })}</ol>; }
  if (question.questionType === 'essay') return <EssayInput disabled={disabled} onSave={onSave} question={question} response={response} saving={saving} />;
  return null;
};

const Result = ({ attempt, onAnother }) => <section className="quiz-result"><p className="eyebrow">Quiz result</p><h2>{resultText(attempt)}</h2>{attempt.pendingManualGrading ? <p>Your automatically graded answers have been processed. Final results will be available after teacher grading.</p> : null}{attempt.score !== undefined ? <dl><div><dt>Score</dt><dd>{attempt.score} / {attempt.maximumScore}</dd></div><div><dt>Percentage</dt><dd>{attempt.percentage}%</dd></div><div><dt>Outcome</dt><dd>{attempt.passed ? 'Pass' : 'Fail'}</dd></div></dl> : <p>Your score is not available for this Quiz.</p>}<button className="button" onClick={onAnother} type="button">Back to Quiz</button></section>;

const QuizAttempt = ({ attemptId, onFinished }) => {
  const queryClient = useQueryClient();
  const [current, setCurrent] = useState(0), [confirming, setConfirming] = useState(false), [time, setTime] = useState(null);
  const attempt = useQuery({ queryKey: queryKeys.learning.quizAttempt(attemptId), queryFn: ({ signal }) => learningApi.quizAttempt(attemptId, signal), refetchInterval: (data) => data?.state?.data?.status === 'in_progress' ? 60000 : false });
  const save = useMutation({ mutationFn: ({ questionId, response }) => learningApi.saveQuizAnswer(attemptId, questionId, response), onSuccess: () => queryClient.invalidateQueries({ queryKey: queryKeys.learning.quizAttempt(attemptId) }) });
  const submit = useMutation({ mutationFn: () => learningApi.submitQuizAttempt(attemptId), onSuccess: (data) => { queryClient.setQueryData(queryKeys.learning.quizAttempt(attemptId), data); queryClient.invalidateQueries({ queryKey: queryKeys.learning.quiz(attempt.data?.quiz?.id) }); onFinished(data); } });
  useEffect(() => { const expiry = attempt.data?.expiresAt; if (!expiry) return undefined; const tick = () => setTime(secondsLeft(expiry)); tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, [attempt.data?.expiresAt]);
  useEffect(() => { if (time === 0 && attempt.data?.status === 'in_progress' && !submit.isPending) submit.mutate(); }, [time, attempt.data?.status, submit]);
  if (attempt.isPending) return <LoadingSkeleton label="Loading quiz attempt" />;
  if (attempt.isError) return <InlineError error={attempt.error} onRetry={attempt.refetch} />;
  const data = attempt.data;
  if (data.status !== 'in_progress') return <Result attempt={data} onAnother={onFinished} />;
  const question = data.questions[current] || data.questions[0], answered = data.questions.filter((item) => item.navigation.answered).length;
  const saveQuestion = (response) => save.mutate({ questionId: question.id, response });
  return <section className="student-quiz-attempt"><header><div><p className="eyebrow">Question {question.number} of {data.questions.length}</p><h2>{data.quiz.title}</h2></div><strong className={`quiz-timer ${time !== null && time <= 300 ? 'warning' : ''}`}>{clock(time)}</strong></header><div className="quiz-attempt-layout"><nav aria-label="Question navigation" className="quiz-navigator">{data.questions.map((item, index) => <button aria-current={index === current ? 'step' : undefined} className={`${index === current ? 'current' : ''} ${item.navigation.answered ? 'answered' : ''}`} key={item.id} onClick={() => setCurrent(index)} type="button">{item.number}<span className="sr-only">{item.navigation.answered ? ', answered' : ', unanswered'}</span></button>)}</nav><main><article className="quiz-question"><p className="quiz-marks">{question.marksAvailable} marks</p><div className="quiz-question-text" dangerouslySetInnerHTML={{ __html: question.questionText }} /><QuestionInput disabled={save.isPending} key={question.id} onSave={saveQuestion} question={question} saving={save.isPending} />{save.error ? <p role="alert">Your answer could not be saved. Please try again.</p> : <p className="quiz-save-state">{save.isPending ? 'Saving…' : question.navigation.answered ? 'Saved' : 'Not answered'}</p>}</article><nav className="quiz-actions" aria-label="Question actions"><button disabled={current === 0} onClick={() => setCurrent(current - 1)} type="button">Previous</button><button disabled={current === data.questions.length - 1} onClick={() => setCurrent(current + 1)} type="button">Next</button><button className="button" onClick={() => setConfirming(true)} type="button">Submit Quiz</button></nav></main></div>{confirming ? <div className="quiz-confirm" role="dialog" aria-modal="true"><h3>Submit Quiz?</h3><p>{answered} of {data.questions.length} questions have been answered. {data.questions.length - answered} remain unanswered.</p><p>{time === null ? 'There is no time limit.' : `${clock(time)} remaining.`}</p><button onClick={() => setConfirming(false)} type="button">Return to questions</button><button className="button" disabled={submit.isPending} onClick={() => submit.mutate()} type="button">Confirm submission</button>{submit.error ? <p role="alert">Unable to submit the Quiz. Please try again.</p> : null}</div> : null}</section>;
};

const ConfiguredStudentQuiz = ({ quizId }) => {
  const [attemptId, setAttemptId] = useState(null), [result, setResult] = useState(null); const queryClient = useQueryClient();
  const quiz = useQuery({ queryKey: queryKeys.learning.quiz(quizId), queryFn: ({ signal }) => learningApi.quiz(quizId, signal), enabled: Boolean(quizId) });
  const start = useMutation({ mutationFn: () => learningApi.startQuizAttempt(quizId), onSuccess: (data) => { queryClient.setQueryData(queryKeys.learning.quizAttempt(data.id), data); setAttemptId(data.id); } });
  if (attemptId) return result ? <Result attempt={result} onAnother={() => { setResult(null); setAttemptId(null); quiz.refetch(); }} /> : <QuizAttempt attemptId={attemptId} onFinished={(data) => { if (data?.id) setResult(data); else { setAttemptId(null); quiz.refetch(); } }} />;
  if (quiz.isPending) return <LoadingSkeleton label="Loading quiz" />;
  if (quiz.isError) return <InlineError error={quiz.error} onRetry={quiz.refetch} />;
  const data = quiz.data, unavailable = data.quiz.availableFrom && new Date(data.quiz.availableFrom) > new Date() || data.quiz.availableUntil && new Date(data.quiz.availableUntil) <= new Date(), exhausted = data.remainingAttempts === 0 && !data.resumableAttemptId;
  return <section className="student-quiz"><header><p className="eyebrow">Quiz</p><h2>{data.quiz.title}</h2>{data.quiz.description ? <p>{data.quiz.description}</p> : null}</header>{data.quiz.instructions ? <div className="quiz-instructions" dangerouslySetInnerHTML={{ __html: data.quiz.instructions }} /> : null}<dl className="quiz-details"><div><dt>Time limit</dt><dd>{data.quiz.timeLimitMinutes ? `${data.quiz.timeLimitMinutes} minutes` : 'No time limit'}</dd></div><div><dt>Attempts</dt><dd>{data.attemptsUsed} used · {data.remainingAttempts} remaining</dd></div><div><dt>Pass mark</dt><dd>{data.quiz.passPercentage}%</dd></div><div><dt>Grading</dt><dd>{data.quiz.gradingMethod}</dd></div></dl>{unavailable ? <p role="status">This Quiz is not currently available.</p> : exhausted ? <p role="status">You have used all allowed attempts.</p> : <button className="button" disabled={start.isPending} onClick={() => data.resumableAttemptId ? setAttemptId(data.resumableAttemptId) : start.mutate()} type="button">{data.resumableAttemptId ? 'Resume attempt' : 'Start Quiz'}</button>}{start.error ? <p role="alert">Unable to start this Quiz. Please try again.</p> : null}{data.attempts.length ? <section className="quiz-history"><h3>Previous attempts</h3><ul>{data.attempts.map((item) => <li key={item.id}>Attempt {item.attemptNumber} · {item.status}{item.percentage !== undefined ? ` · ${item.percentage}%` : ''}</li>)}</ul></section> : null}</section>;
};

export const StudentQuiz = ({ quizId }) => quizId ? <ConfiguredStudentQuiz quizId={quizId} /> : <p role="alert">This Quiz has not been configured yet.</p>;
